// Import stuff from Zod 4.x
import { toJSONSchema, ZodObject, ZodType } from 'zod';

// Import types
import type {
    ServerOptions,
    RouteDefinition,
    MethodSchema,
    OpenAPIMeta,
    RequestHandler,
    OpenAPIConfig,
    OpenAPIObject,
    JsonSchemaConverter,
} from '../types/index.js';
import type { SchemaInput } from '../validation/types.js';

/**
 * Builds OpenAPI parameters from a Zod object schema, using the input side so
 * `.default()` / `.optional()` fields are not required and each parameter
 * keeps its enum / format / default / min / max.
 */
function buildParameters(
    zodSchema: unknown,
    location: 'path' | 'query' | 'header' | 'cookie'
): any[] {
    if (!isZodObjectSchema(zodSchema)) return [];

    const json = toJSONSchema(zodSchema, {
        io: 'input',
        unrepresentable: 'any',
    }) as {
        properties?: Record<string, Record<string, unknown>>;
        required?: string[];
    };
    const required = new Set(json.required ?? []);

    return Object.entries(json.properties ?? {}).map(([name, schema]) => {
        const { description, ...rest } = schema;
        return {
            name,
            in: location,
            // OpenAPI requires path parameters to be marked required.
            required: location === 'path' || required.has(name),
            schema: rest,
            description:
                typeof description === 'string'
                    ? description
                    : `${location} parameter ${name}`,
        };
    });
}

function isZodObjectSchema(value: unknown): value is ZodObject<any, any> {
    return value instanceof ZodObject;
}

/**
 * Converts a SchemaInput to JSON Schema: configured converter first, Zod's
 * `toJSONSchema` as fallback.
 *
 * `io` selects the request side (`'input'`, where `.default()` fields are
 * optional) or the response side (`'output'`).
 */
function schemaToJsonSchema(
    schema: SchemaInput,
    mapJsonSchema?: Record<string, JsonSchemaConverter>,
    io: 'input' | 'output' = 'output'
): Record<string, unknown> | undefined {
    if (schema instanceof ZodType) {
        const jsonSchema = toJSONSchema(schema, {
            io,
            unrepresentable: 'any',
        }) as Record<string, unknown>;
        // Zod emits `$schema`, which is illegal inside an OpenAPI `schema`
        // object (OAS defines its own dialect) — drop it.
        delete jsonSchema.$schema;
        return jsonSchema;
    }
    // Standard Schema: try configured converters
    if (mapJsonSchema && typeof schema === 'object' && schema !== null) {
        const stdSchema = schema as unknown as Record<string, unknown>;
        const vendor =
            (stdSchema['~standard'] as Record<string, unknown>)?.vendor ??
            stdSchema.__vendor;
        if (typeof vendor === 'string' && mapJsonSchema[vendor]) {
            return mapJsonSchema[vendor](schema);
        }
    }
    return undefined;
}

/**
 * Builds a request body object for OpenAPI based on a SchemaInput.
 */
function buildRequestBody(
    zodSchema: unknown,
    mapJsonSchema?: Record<string, JsonSchemaConverter>
): any {
    if (!(zodSchema instanceof ZodType) && !isStandardSchema(zodSchema))
        return undefined;
    const jsonSchema = schemaToJsonSchema(
        zodSchema as SchemaInput,
        mapJsonSchema,
        'input'
    );
    if (!jsonSchema) return undefined;
    return {
        content: {
            'application/json': {
                schema: jsonSchema,
            },
        },
        description: 'Request body',
        required: true,
    };
}

/**
 * Type guard for Standard Schema objects (has ~standard property).
 */
function isStandardSchema(value: unknown): value is Record<string, unknown> {
    return typeof value === 'object' && value !== null && '~standard' in value;
}

/**
 * Builds OpenAPI responses from a route's response schema, converting each
 * status code's schema to JSON Schema.
 */
function buildResponses(
    responseSchema: Record<string, SchemaInput> | undefined,
    openapiMetaResponses: Record<string, any> | undefined,
    mapJsonSchema?: Record<string, JsonSchemaConverter>
): Record<string, any> {
    // Auto-generate from schema.response
    const autoGenerated: Record<string, any> = {};
    if (responseSchema) {
        for (const [statusCode, schema] of Object.entries(responseSchema)) {
            const jsonSchema = schemaToJsonSchema(schema, mapJsonSchema);
            autoGenerated[statusCode] = {
                description: statusCode.startsWith('2')
                    ? 'Successful response'
                    : statusCode.startsWith('4')
                      ? 'Client error'
                      : statusCode.startsWith('5')
                        ? 'Server error'
                        : `Response ${statusCode}`,
                content: jsonSchema
                    ? {
                          'application/json': {
                              schema: jsonSchema,
                          },
                      }
                    : undefined,
            };
        }
    }

    // User-provided responses override auto-generated ones.
    if (openapiMetaResponses) {
        return { ...autoGenerated, ...openapiMetaResponses };
    }

    return Object.keys(autoGenerated).length > 0
        ? autoGenerated
        : { '200': { description: 'Successful response' } };
}

/**
 * Converts `:param` and `*` route segments to OpenAPI's curly brace syntax.
 */
function convertPathForOpenAPI(routePath: string): string {
    if (routePath.indexOf(':') === -1 && routePath.indexOf('*') === -1) {
        return routePath;
    }
    return routePath
        .replace(/:([a-zA-Z0-9_]+)/g, '{$1}')
        .replace(/\*+/g, '{path}');
}

/**
 * Generates a full OpenAPI 3.0 document from API routes.
 *
 * @param apiRoutes Compiled route definitions.
 * @param options Server options (fallback metadata source).
 * @param config OpenAPI config from `openapi.config.ts` (primary metadata source).
 */
export function generateOpenAPIDocument(
    apiRoutes: RouteDefinition[],
    options: ServerOptions,
    config?: OpenAPIConfig
): OpenAPIObject {
    // Build info block: config overrides ServerOptions
    const info: Record<string, any> = {
        title: config?.title || options.title || 'Burger API',
        description:
            config?.description ||
            options.description ||
            'Burger API documentation',
        version: config?.version || options.version || '1.0.0',
    };
    if (config?.contact) info.contact = config.contact;
    if (config?.license) info.license = config.license;
    if (config?.termsOfService) info.termsOfService = config.termsOfService;

    const doc: OpenAPIObject = {
        openapi: '3.0.0',
        info,
        paths: {} as Record<string, any>,
    };

    // Servers
    if (config?.servers && config.servers.length > 0) {
        doc.servers = config.servers;
    }

    // External docs
    if (config?.externalDocs) {
        doc.externalDocs = config.externalDocs;
    }

    // Root security defaults to `[]` (no auth required): core is auth-agnostic,
    // and omitting it makes strict linters flag every operation.
    doc.security =
        config?.security && config.security.length > 0
            ? config.security
            : [];

    // Collect tags used across operations
    const tagSet = new Set<string>();
    // OperationIds must be unique and sanitized for OpenAPI
    // (`^[a-zA-Z0-9_.-]+$`); collisions get a numeric suffix.
    const usedOperationIds = new Set<string>();

    for (const route of apiRoutes) {
        const openApiPath = convertPathForOpenAPI(route.path);
        doc.paths[openApiPath] = doc.paths[openApiPath] || {};

        for (const method in route.handlers) {
            // Handler/schema/openapi maps are union-keyed at the type level,
            // so widen per map for runtime lookups.
            const handlers = route.handlers as Record<string, RequestHandler>;
            const openapiMeta = (route.openapi ?? {}) as Record<
                string,
                OpenAPIMeta
            >;
            const schema = (route.schema ?? {}) as Record<
                string,
                MethodSchema
            >;

            if (typeof handlers[method] !== 'function') continue;
            // Auto-generated OPTIONS (CORS preflight) is not a documented
            // operation.
            if ((handlers[method] as { isAutoOptions?: boolean }).isAutoOptions) {
                continue;
            }
            const lowerMethod = method.toLowerCase();

            try {
                const methodMeta = openapiMeta[lowerMethod] || {};

                // Sanitize the operationId to OpenAPI-legal characters and
                // dedupe collisions.
                let operationId =
                    methodMeta.operationId ||
                    `${lowerMethod}_${route.path.replace(/[^a-zA-Z0-9_.-]+/g, '_')}`;
                if (usedOperationIds.has(operationId)) {
                    let suffix = 2;
                    let candidate = `${operationId}_${suffix}`;
                    while (usedOperationIds.has(candidate)) {
                        suffix += 1;
                        candidate = `${operationId}_${suffix}`;
                    }
                    operationId = candidate;
                }
                usedOperationIds.add(operationId);

                let parameters: any[] = [];
                if (schema[lowerMethod]) {
                    const schemaDef = schema[lowerMethod];
                    parameters = [
                        ...buildParameters(schemaDef.params, 'path'),
                        ...buildParameters(schemaDef.query, 'query'),
                        ...buildParameters(schemaDef.headers, 'header'),
                        ...buildParameters(schemaDef.cookies, 'cookie'),
                    ];
                }

                // Every operation on a templated path must define its path
                // parameters (OAS `path-parameters-defined`), even with no
                // schema.
                for (const match of openApiPath.matchAll(/\{([^}]+)\}/g)) {
                    const name = match[1]!;
                    if (
                        !parameters.some(
                            (p) => p.in === 'path' && p.name === name
                        )
                    ) {
                        parameters.unshift({
                            name,
                            in: 'path',
                            required: true,
                            schema: { type: 'string' },
                            description: `Path parameter ${name}`,
                        });
                    }
                }

                let requestBody = undefined;
                if (schema[lowerMethod]?.body) {
                    requestBody = buildRequestBody(
                        schema[lowerMethod].body,
                        config?.mapJsonSchema
                    );
                }

                const responses = buildResponses(
                    schema[lowerMethod]?.response,
                    methodMeta.responses,
                    config?.mapJsonSchema
                );

                // Collect tags
                const tags = methodMeta.tags || [];
                for (const tag of tags) {
                    tagSet.add(tag);
                }

                (doc.paths[openApiPath] as any)[lowerMethod] = {
                    operationId,
                    summary:
                        methodMeta.summary ||
                        `Summary for ${method} ${route.path}`,
                    description: methodMeta.description || '',
                    tags,
                    deprecated: methodMeta.deprecated || false,
                    parameters,
                    requestBody,
                    responses,
                    externalDocs: methodMeta.externalDocs || undefined,
                };
            } catch (error) {
                // A schema the converter still cannot express must not take
                // the whole document (or startup) down — document the
                // operation with an empty object and warn once.
                console.warn(
                    `[burger-api] OpenAPI: could not build ${method.toUpperCase()} ${route.path} — documenting it without schema details:`,
                    error
                );
                (doc.paths[openApiPath] as any)[lowerMethod] = {};
            }
        }
    }

    // Emit the top-level tags array.
    if (tagSet.size > 0) {
        (doc as any).tags = Array.from(tagSet).map((name) => ({ name }));
    }

    // Add components.schemas.ProblemDetail (RFC 9457) when the doc has paths.
    if (Object.keys(doc.paths).length > 0) {
        (doc as any).components = {
            schemas: {
                ProblemDetail: {
                    type: 'object',
                    properties: {
                        type: {
                            type: 'string',
                            description:
                                'URI reference identifying the problem type',
                        },
                        title: {
                            type: 'string',
                            description: 'Short human-readable summary',
                        },
                        status: {
                            type: 'integer',
                            description: 'HTTP status code',
                        },
                        detail: {
                            type: 'string',
                            description: 'Human-readable explanation',
                        },
                    },
                    required: ['type', 'title', 'status'],
                },
            },
        };
    }

    return doc;
}
