/**
 * Generate the in-memory virtual entrypoint source for Bun.build().
 * Uses static imports so the bundler traces and embeds all route modules.
 */

import type { BuildConfig } from '../types/index';
import type { ApiRouteScanEntry, PageRouteScanEntry } from './scanner';

const HTTP_METHODS = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD'];

const PREFLIGHT_METHODS = ['POST', 'PUT', 'DELETE', 'PATCH'];

function methodsToEmit(entry: ApiRouteScanEntry): string[] {
    if (entry.methods && entry.methods.length > 0) {
        return entry.methods;
    }
    return [...HTTP_METHODS];
}

function pushImportLines(
    lines: string[],
    entries: { importPath: string }[],
    variablePrefix: 'r' | 'p'
): void {
    entries.forEach((entry, index) => {
        lines.push(
            `import * as _${variablePrefix}${index} from '${entry.importPath}';`
        );
    });
}

/**
 * Generate virtual entrypoint source that imports all routes and starts Burger with apiRoutes/pageRoutes.
 */
export function generateVirtualEntrySource(
    config: BuildConfig,
    apiEntries: ApiRouteScanEntry[],
    pageEntries: PageRouteScanEntry[],
    optionsImportPath?: string
): string {
    const lines: string[] = [];

    lines.push('// Auto-generated by burger-api build. Do not edit.');
    lines.push("import { Burger } from 'burger-api';");
    if (optionsImportPath) {
        lines.push(
            `import { burgerOptions as __burgerOptions } from '${optionsImportPath}';`
        );
    }
    lines.push('');
    // Ensure CWD matches the bundle directory so HTML chunk paths resolve correctly
    lines.push('process.chdir(import.meta.dir);');
    lines.push('');

    pushImportLines(lines, apiEntries, 'r');
    if (pageEntries.length) {
        lines.push('');
        pushImportLines(lines, pageEntries, 'p');
    }

    lines.push('');
    lines.push('const apiRoutes = [');

    apiEntries.forEach((e, i) => {
        const methods = methodsToEmit(e);
        const hasPreflight = PREFLIGHT_METHODS.some((m) => methods.includes(m));
        const hasOptions = methods.includes('OPTIONS');

        lines.push('  {');
        lines.push(`    path: ${JSON.stringify(e.routePath)},`);
        lines.push('    handlers: {');
        for (const m of methods) {
            if (m === 'OPTIONS') continue;
            lines.push(`      ${m}: _r${i}.${m},`);
        }
        if (hasOptions) {
            lines.push(`      OPTIONS: _r${i}.OPTIONS,`);
        } else if (hasPreflight) {
            lines.push(
                `      OPTIONS: () => new Response(null, { status: 204 }),`
            );
        }
        lines.push('    },');
        lines.push(`    middleware: _r${i}.middleware,`);
        lines.push(`    schema: _r${i}.schema,`);
        lines.push(`    openapi: _r${i}.openapi,`);
        lines.push(`    isWildcard: ${e.isWildcard},`);
        lines.push('  },');
    });

    lines.push('];');
    lines.push('');

    lines.push('const pageRoutes = [');
    pageEntries.forEach((p, i) => {
        lines.push(
            `  { path: ${JSON.stringify(p.routePath)}, handler: _p${i}.default },`
        );
        if (p.routePath !== '/' && !p.routePath.endsWith('/')) {
            lines.push(
                `  { path: ${JSON.stringify(p.routePath + '/')}, handler: _p${i}.default },`
            );
        }
    });
    lines.push('];');
    lines.push('');

    lines.push('const app = new Burger({');
    if (optionsImportPath) {
        lines.push('  ...__burgerOptions,');
    } else {
        lines.push(`  debug: ${config.debug === true},`);
    }
    lines.push('  apiRoutes,');
    lines.push('  pageRoutes,');
    lines.push('});');
    lines.push('');
    lines.push('const port = Number(process.env.PORT) || 4000;');
    lines.push('app.serve(port, () => {');
    lines.push('  console.log(`Server running on http://localhost:${port}`);');
    lines.push('});');

    return lines.join('\n');
}
