/**
 * Generate the in-memory virtual entrypoint source for Bun.build().
 * Uses static imports so the bundler traces and embeds all route modules.
 *
 * Vision: each route directory is self-contained — no global tier hooks.
 * Groups only affect URL path stripping.
 */

import type { BuildConfig, RuntimeTarget } from '../types/index';
import type {
    ApiRouteScanEntry,
    PageRouteScanEntry,
    WebSocketRouteScanEntry,
    AssetRouteScanEntry,
} from './scanner';
import { readFileSync } from 'fs';

/** Paths to app-level convention files for production builds. */
export interface AppConventionPaths {
    /** Path to `src/hooks.ts` — exports all 6 hook points */
    hooksPath?: string;
    /** Path to `src/plugins.ts` — default export: (burger: PluginRegistrar) => void */
    pluginsPath?: string;
    /** Path to `src/providers.ts` — default export: (burger: ProviderRegistrar) => void */
    providersPath?: string;
    /** Path to `src/openapi.config.ts` — default export: OpenAPIConfig */
    openapiConfigPath?: string;
}

function pushImportLines(
    lines: string[],
    entries: { importPath: string }[],
    variablePrefix: 'r' | 'p'
): void {
    entries.forEach((entry, index) => {
        lines.push(
            `import * as _${variablePrefix}${index} from '${entry.importPath}';`
        );
    });
}

/**
 * Generate virtual entrypoint source that imports all routes and starts Burger with apiRoutes/pageRoutes.
 */
export function generateVirtualEntrySource(
    config: BuildConfig,
    apiEntries: ApiRouteScanEntry[],
    pageEntries: PageRouteScanEntry[],
    optionsImportPath?: string,
    appConventions?: AppConventionPaths,
    wsEntries: WebSocketRouteScanEntry[] = [],
    assetEntries: AssetRouteScanEntry[] = [],
    compile?: boolean,
    target: RuntimeTarget = 'bun'
): string {
    const lines: string[] = [];
    const isPortableTarget =
        target === 'cloudflare' || target === 'deno' || target === 'vercel';

    lines.push('// Auto-generated by burger-api build. Do not edit.');
    lines.push("import { Burger } from 'burger-api';");
    if (isPortableTarget) {
        lines.push("import { toFetchHandler } from 'burger-api';");
    } else if (target === 'node') {
        lines.push("import { serve } from '@burger-api/node-server';");
    }
    if (compile) {
        // `Server`'s own adapter loader (`core/server.ts`) resolves the Bun
        // adapter via a deliberately non-static specifier
        // (`['burger-api','adapter','bun'].join('/')`) so bundlers never pull
        // `import 'bun'` into WinterCG (Cloudflare/Vercel/Deno) bundles. A
        // `--compile` binary has no filesystem/node_modules to fall back to
        // at runtime, though, and Bun's compiler can only embed a dynamic
        // import whose specifier is a literal string at the call site — a
        // computed one is left unresolved and crashes on start
        // ("Cannot find module 'burger-api/adapter/bun'"). `build:exec`
        // output only ever runs standalone under Bun (that's the point of
        // compiling it), so it's always safe to import the adapter
        // statically here and hand it to `Burger` via the existing
        // `ServerOptions.adapter` injection seam, bypassing that dynamic
        // import entirely for this one build target.
        lines.push(
            "import { BunAdapter as __BunAdapter } from 'burger-api/adapter/bun';"
        );
    }
    if (optionsImportPath) {
        lines.push(
            `import { burgerOptions as __burgerOptions } from '${optionsImportPath}';`
        );
    }
    lines.push('');
    if (target === 'bun') {
        // Ensure CWD matches the bundle directory so HTML chunk paths
        // resolve correctly. `import.meta.dir` is a Bun-only extension —
        // every other target either has no filesystem-relative chunking to
        // resolve (portable targets) or runs the bundle in a real Node
        // process where this line would throw, so it's Bun-only.
        lines.push('process.chdir(import.meta.dir);');
        lines.push('');
    }

    pushImportLines(lines, apiEntries, 'r');
    if (pageEntries.length) {
        lines.push('');
        pushImportLines(lines, pageEntries, 'p');
    }

    // Import WebSocket route modules and their sibling convention files.
    // Without this, file-based ws.ts routes are silently dropped from
    // production builds (they exist only in the dev filesystem scan).
    if (wsEntries.length) {
        lines.push('');
        wsEntries.forEach((w, i) => {
            lines.push(`import * as _w${i} from '${w.importPath}';`);
            if (w.hooksPath) {
                lines.push(`import * as _wh${i} from '${w.hooksPath}';`);
            }
            if (w.configPath) {
                lines.push(`import * as _wc${i} from '${w.configPath}';`);
            }
        });
    }

    // Import a sibling `hooks.ts` for any route that declares lifecycle hooks
    //. Each route is self-contained — no global tier merging.
    apiEntries.forEach((e, i) => {
        if (e.hooksPath) {
            lines.push(`import * as _h${i} from '${e.hooksPath}';`);
        }
    });

    // Import per-route convention files (schema, openapi, config) for
    // build-time merging. These are separate from route.ts.
    apiEntries.forEach((e, i) => {
        if (e.schemaPath) {
            lines.push(`import * as _s${i} from '${e.schemaPath}';`);
        }
        if (e.openapiPath) {
            lines.push(`import * as _o${i} from '${e.openapiPath}';`);
        }
        if (e.configPath) {
            lines.push(`import * as _c${i} from '${e.configPath}';`);
        }
    });
    // Handlers and convention exports are read from the module namespaces
    // at startup — never guessed from source text at build time — so every
    // export style (`export const GET: Handler = ...`, `export { GET }`,
    // `defineRoute(...)`, typed or destructured hooks) behaves as in dev
    // (framework ModuleLoader: `mod.default ?? mod`, function-valued method
    // exports). Optional exports are read through a helper parameter, so
    // bundlers (wrangler, esbuild) don't warn about imports that are
    // legitimately undefined.
    if (apiEntries.length || wsEntries.length) {
        lines.push('');
        lines.push('function __mod(mod) {');
        lines.push(' return mod.default ?? mod;');
        lines.push('}');
        lines.push('function __get(mod, key) {');
        lines.push(' return mod[key];');
        lines.push('}');
        lines.push('function __pick(mod, keys) {');
        lines.push(' const out = {};');
        lines.push(' for (const k of keys) {');
        lines.push("  if (typeof mod[k] === 'function') out[k] = mod[k];");
        lines.push(' }');
        lines.push(' return out;');
        lines.push('}');
    }
    if (apiEntries.length) {
        // The framework adds its own OPTIONS handler (204 + Allow) to every
        // route at compile time and skips beforeRoute for it — emitting one
        // here would override that and bypass the router's preflight logic.
        lines.push('function __handlers(mod) {');
        lines.push(
            " return __pick(mod, ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS']);"
        );
        lines.push('}');
        lines.push('function __normOpenapi(mod) {');
        lines.push(' if (!mod) return mod;');
        lines.push(' const out = {};');
        lines.push(' for (const k of Object.keys(mod)) {');
        lines.push(
            ' out[/^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS)$/.test(k) ? k.toLowerCase() : k] = mod[k];'
        );
        lines.push(' }');
        lines.push(' return out;');
        lines.push('}');
    }
    // HTML pages are imported as raw strings (see bun.ts's `.html` text
    // loader, matching dev's `?raw` import), but Bun.serve's routes map only
    // accepts functions/HTMLBundles/Responses. Wrap non-function defaults
    // into a text/html Response factory — exactly what the dev PageRouter
    // does for string page modules.
    if (pageEntries.length) {
        lines.push('function __page(mod) {');
        lines.push(' const h = mod.default;');
        lines.push(" if (typeof h === 'function') return h;");
        lines.push(
            " return () => new Response(h, { headers: { 'Content-Type': 'text/html; charset=utf-8' } });"
        );
        lines.push('}');
    }

    // Import app-level convention files for production builds
    if (appConventions) {
        if (appConventions.hooksPath) {
            lines.push(
                `import * as __globalHooks from '${appConventions.hooksPath}';`
            );
        }
        if (appConventions.pluginsPath) {
            lines.push(
                `import * as __pluginsModule from '${appConventions.pluginsPath}';`
            );
        }
        if (appConventions.providersPath) {
            lines.push(
                `import * as __providersModule from '${appConventions.providersPath}';`
            );
        }
        if (appConventions.openapiConfigPath) {
            lines.push(
                `import __openapiConfig from '${appConventions.openapiConfigPath}';`
            );
        }
    }

    lines.push('');
    lines.push('const apiRoutes = [');

    apiEntries.forEach((e, i) => {
        lines.push(' {');
        lines.push(` path: ${JSON.stringify(e.routePath)},`);
        lines.push(` handlers: __handlers(_r${i}),`);
        lines.push(
            ` schema: ${e.schemaPath ? `__mod(_s${i})` : `__get(_r${i}, 'schema')`},`
        );
        lines.push(
            ` openapi: ${e.openapiPath ? `__normOpenapi(__mod(_o${i}))` : `__get(_r${i}, 'openapi')`},`
        );
        lines.push(
            ` config: ${e.configPath ? `__mod(_c${i})` : `__get(_r${i}, 'config')`},`
        );
        lines.push(
            ` hooks: ${e.hooksPath ? `__mod(_h${i})` : `__get(_r${i}, 'hooks')`},`
        );
        lines.push(` isWildcard: ${e.isWildcard},`);
        lines.push(' },');
    });

    lines.push('];');
    lines.push('');

    lines.push('const pageRoutes = [');
    pageEntries.forEach((p, i) => {
        lines.push(
            ` { path: ${JSON.stringify(p.routePath)}, handler: __page(_p${i}) },`
        );
        if (p.routePath !== '/' && !p.routePath.endsWith('/')) {
            lines.push(
                ` { path: ${JSON.stringify(p.routePath + '/')}, handler: __page(_p${i}) },`
            );
        }
    });
    lines.push('];');
    lines.push('');

    if (wsEntries.length) {
        lines.push('const wsRoutes = [');
        wsEntries.forEach((w, i) => {
            lines.push(' {');
            lines.push(` path: ${JSON.stringify(w.routePath)},`);
            lines.push(
                ` handlers: __pick(_w${i}, ['open', 'message', 'close', 'drain', 'ping', 'pong']),`
            );
            if (w.hooksPath) {
                lines.push(
                    ` hooks: __pick(_wh${i}, ['onOpen', 'onMessage', 'onClose']),`
                );
            }
            if (w.configPath) {
                lines.push(` config: __mod(_wc${i}),`);
            }
            lines.push(' },');
        });
        lines.push('];');
        lines.push('');
    }

    lines.push('const app = new Burger({');
    // Declares the deployment target so WebSocket upgrade handling can trust
    // it over live `globalThis` detection — the only way to give an accurate
    // answer on targets (Node vs. Vercel) indistinguishable at request time.
    lines.push(` runtimeTarget: ${JSON.stringify(target)},`);
    if (compile) {
        // Emitted before any user-supplied options so an explicit
        // `adapter` in burgerOptions.ts (rare, but a valid override) still
        // wins — object-literal keys resolve last-write-wins.
        lines.push(' adapter: new __BunAdapter(),');
    }
    // Always explicit: an unbundled production entry (deno, vercel,
    // wrangler dev) must never fall back to dev-mode error output. An
    // explicit `debug` in the entry file's options still wins (spread last).
    lines.push(` debug: ${config.debug === true},`);
    if (optionsImportPath) {
        lines.push(' ...__burgerOptions,');
    }
    if (appConventions?.hooksPath) {
        lines.push(' globalHooks: __globalHooks,');
    }
    if (appConventions?.pluginsPath) {
        lines.push(' pluginsModule: __pluginsModule,');
    }
    if (appConventions?.providersPath) {
        lines.push(' providersModule: __providersModule,');
    }
    if (appConventions?.openapiConfigPath) {
        lines.push(' openapi: __openapiConfig,');
    }
    lines.push(' apiRoutes,');
    lines.push(' pageRoutes,');
    if (wsEntries.length) {
        lines.push(' wsRoutes,');
    }
    if (assetEntries.length) {
        // Static assets are base64-embedded at build time so the bundle
        // stays self-contained (no filesystem access at runtime).
        lines.push(' assetRoutes: [');
        for (const asset of assetEntries) {
            const data = readFileSync(asset.absolutePath).toString('base64');
            lines.push(
                `  { path: ${JSON.stringify(asset.routePath)}, contentType: ${JSON.stringify(asset.contentType)}, data: ${JSON.stringify(data)} },`
            );
        }
        lines.push(' ],');
    }
    lines.push('});');
    lines.push('');
    if (isPortableTarget) {
        // Cloudflare Workers / Deno Deploy / Vercel: no long-running process
        // to bind a port to — the platform calls `fetch` per request. The
        // platform's own tool (wrangler / deno / vercel) bundles this file;
        // Bun.build never runs for this target.
        if (target === 'vercel') {
            // Without this, Vercel defaults to the Edge runtime, which
            // rejects the plain `export default { fetch }` shape.
            lines.push("export const runtime = 'nodejs';");
            lines.push('');
        }
        lines.push('export default { fetch: toFetchHandler(app) };');
    } else if (target === 'node') {
        lines.push('const port = Number(process.env.PORT) || 4000;');
        lines.push('serve(app, { port });');
        lines.push('console.log(`Server running on http://localhost:${port}`);');
    } else {
        lines.push('const port = Number(process.env.PORT) || 4000;');
        lines.push('app.serve(port, () => {');
        lines.push(
            ' console.log(`Server running on http://localhost:${port}`);'
        );
        lines.push('});');
    }

    return lines.join('\n');
}
