/**
 * Generate the in-memory virtual entrypoint source for Bun.build().
 * Uses static imports so the bundler traces and embeds all route modules.
 *
 * Vision: each route directory is self-contained — no global tier hooks.
 * Groups only affect URL path stripping.
 */

import type { BuildConfig } from '../types/index';
import type {
    ApiRouteScanEntry,
    PageRouteScanEntry,
    WebSocketRouteScanEntry,
    AssetRouteScanEntry,
} from './scanner';
import { readFileSync } from 'fs';

/** Paths to app-level convention files for production builds. */
export interface AppConventionPaths {
    /** Path to `src/hooks.ts` — exports all 6 hook points */
    hooksPath?: string;
    /** Path to `src/plugins.ts` — default export: (burger: Burger) => void */
    pluginsPath?: string;
    /** Path to `src/providers.ts` — default export: (burger: Burger) => void */
    providersPath?: string;
    /** Path to `src/openapi.config.ts` — default export: OpenAPIConfig */
    openapiConfigPath?: string;
}

/** Default methods to emit when entry has no methods; excludes OPTIONS so we add 204 only when hasPreflight. */
const DEFAULT_EMIT_METHODS = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD'];

const PREFLIGHT_METHODS = ['POST', 'PUT', 'DELETE', 'PATCH'];

function methodsToEmit(entry: ApiRouteScanEntry): string[] {
    if (entry.methods && entry.methods.length > 0) {
        return entry.methods;
    }
    return [...DEFAULT_EMIT_METHODS];
}

function pushImportLines(
    lines: string[],
    entries: { importPath: string }[],
    variablePrefix: 'r' | 'p'
): void {
    entries.forEach((entry, index) => {
        lines.push(
            `import * as _${variablePrefix}${index} from '${entry.importPath}';`
        );
    });
}

/**
 * Generate virtual entrypoint source that imports all routes and starts Burger with apiRoutes/pageRoutes.
 */
export function generateVirtualEntrySource(
    config: BuildConfig,
    apiEntries: ApiRouteScanEntry[],
    pageEntries: PageRouteScanEntry[],
    optionsImportPath?: string,
    appConventions?: AppConventionPaths,
    wsEntries: WebSocketRouteScanEntry[] = [],
    assetEntries: AssetRouteScanEntry[] = []
): string {
    const lines: string[] = [];

    lines.push('// Auto-generated by burger-api build. Do not edit.');
    lines.push("import { Burger } from 'burger-api';");
    if (optionsImportPath) {
        lines.push(
            `import { burgerOptions as __burgerOptions } from '${optionsImportPath}';`
        );
    }
    lines.push('');
    // Ensure CWD matches the bundle directory so HTML chunk paths resolve correctly
    lines.push('process.chdir(import.meta.dir);');
    lines.push('');

    pushImportLines(lines, apiEntries, 'r');
    if (pageEntries.length) {
        lines.push('');
        pushImportLines(lines, pageEntries, 'p');
    }

    // Import WebSocket route modules and their sibling convention files.
    // Without this, file-based ws.ts routes are silently dropped from
    // production builds (they exist only in the dev filesystem scan).
    if (wsEntries.length) {
        lines.push('');
        wsEntries.forEach((w, i) => {
            lines.push(`import * as _w${i} from '${w.importPath}';`);
            if (w.hooksPath) {
                lines.push(`import * as _wh${i} from '${w.hooksPath}';`);
            }
            if (w.configPath) {
                lines.push(`import * as _wc${i} from '${w.configPath}';`);
            }
        });
    }

    // Import a sibling `hooks.ts` for any route that declares lifecycle hooks
    //. Each route is self-contained — no global tier merging.
    apiEntries.forEach((e, i) => {
        if (e.hooksPath) {
            lines.push(`import * as _h${i} from '${e.hooksPath}';`);
        }
    });

    // Import per-route convention files (schema, openapi, config) for
    // build-time merging. These are separate from route.ts.
    const hasOpenapiEntry = apiEntries.some((e) => e.openapiPath);
    apiEntries.forEach((e, i) => {
        if (e.schemaPath) {
            lines.push(`import * as _s${i} from '${e.schemaPath}';`);
        }
        if (e.openapiPath) {
            lines.push(`import * as _o${i} from '${e.openapiPath}';`);
        }
        if (e.configPath) {
            lines.push(`import * as _c${i} from '${e.configPath}';`);
        }
    });
    if (hasOpenapiEntry) {
        lines.push('');
        lines.push('function __normOpenapi(mod) {');
        lines.push(' const out = {};');
        lines.push(' for (const k of Object.keys(mod)) {');
        lines.push(
            ' out[/^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS)$/.test(k) ? k.toLowerCase() : k] = mod[k];'
        );
        lines.push(' }');
        lines.push(' return out;');
        lines.push('}');
    }

    // Import app-level convention files for production builds
    if (appConventions) {
        if (appConventions.hooksPath) {
            lines.push(
                `import * as __globalHooks from '${appConventions.hooksPath}';`
            );
        }
        if (appConventions.pluginsPath) {
            lines.push(
                `import * as __pluginsModule from '${appConventions.pluginsPath}';`
            );
        }
        if (appConventions.providersPath) {
            lines.push(
                `import * as __providersModule from '${appConventions.providersPath}';`
            );
        }
        if (appConventions.openapiConfigPath) {
            lines.push(
                `import __openapiConfig from '${appConventions.openapiConfigPath}';`
            );
        }
    }

    lines.push('');
    lines.push('const apiRoutes = [');

    apiEntries.forEach((e, i) => {
        const methods = methodsToEmit(e);
        const hasPreflight = PREFLIGHT_METHODS.some((m) => methods.includes(m));

        lines.push(' {');
        lines.push(` path: ${JSON.stringify(e.routePath)},`);
        lines.push(' handlers: {');
        for (const m of methods) {
            lines.push(` ${m}: _r${i}.${m},`);
        }
        if (!methods.includes('OPTIONS') && hasPreflight) {
            lines.push(` OPTIONS: () => new Response(null, { status: 204 }),`);
        }
        lines.push(' },');
        lines.push(` schema: ${e.schemaPath ? `_s${i}` : `_r${i}.schema`},`);
        lines.push(
            ` openapi: ${e.openapiPath ? `__normOpenapi(_o${i})` : `_r${i}.openapi`},`
        );
        lines.push(` config: ${e.configPath ? `_c${i}` : `_r${i}.config`},`);
        lines.push(` hooks: ${e.hooksPath ? `_h${i}` : `_r${i}.hooks`},`);
        lines.push(` isWildcard: ${e.isWildcard},`);
        lines.push(' },');
    });

    lines.push('];');
    lines.push('');

    lines.push('const pageRoutes = [');
    pageEntries.forEach((p, i) => {
        lines.push(
            ` { path: ${JSON.stringify(p.routePath)}, handler: _p${i}.default },`
        );
        if (p.routePath !== '/' && !p.routePath.endsWith('/')) {
            lines.push(
                ` { path: ${JSON.stringify(p.routePath + '/')}, handler: _p${i}.default },`
            );
        }
    });
    lines.push('];');
    lines.push('');

    if (wsEntries.length) {
        lines.push('const wsRoutes = [');
        wsEntries.forEach((w, i) => {
            lines.push(' {');
            lines.push(` path: ${JSON.stringify(w.routePath)},`);
            lines.push(' handlers: {');
            lines.push(`  open: _w${i}.open,`);
            lines.push(`  message: _w${i}.message,`);
            lines.push(`  close: _w${i}.close,`);
            lines.push(`  drain: _w${i}.drain,`);
            lines.push(`  ping: _w${i}.ping,`);
            lines.push(`  pong: _w${i}.pong,`);
            lines.push(' },');
            if (w.hooksPath) {
                lines.push(' hooks: {');
                lines.push(`  onOpen: _wh${i}.onOpen,`);
                lines.push(`  onMessage: _wh${i}.onMessage,`);
                lines.push(`  onClose: _wh${i}.onClose,`);
                lines.push(' },');
            }
            if (w.configPath) {
                lines.push(` config: _wc${i}.default ?? _wc${i},`);
            }
            lines.push(' },');
        });
        lines.push('];');
        lines.push('');
    }

    lines.push('const app = new Burger({');
    if (optionsImportPath) {
        lines.push(' ...__burgerOptions,');
    } else {
        lines.push(` debug: ${config.debug === true},`);
    }
    if (appConventions?.hooksPath) {
        lines.push(' globalHooks: __globalHooks,');
    }
    if (appConventions?.pluginsPath) {
        lines.push(' pluginsModule: __pluginsModule,');
    }
    if (appConventions?.providersPath) {
        lines.push(' providersModule: __providersModule,');
    }
    if (appConventions?.openapiConfigPath) {
        lines.push(' openapi: __openapiConfig,');
    }
    lines.push(' apiRoutes,');
    lines.push(' pageRoutes,');
    if (wsEntries.length) {
        lines.push(' wsRoutes,');
    }
    if (assetEntries.length) {
        // Static assets are base64-embedded at build time so the bundle
        // stays self-contained (no filesystem access at runtime).
        lines.push(' assetRoutes: [');
        for (const asset of assetEntries) {
            const data = readFileSync(asset.absolutePath).toString('base64');
            lines.push(
                `  { path: ${JSON.stringify(asset.routePath)}, contentType: ${JSON.stringify(asset.contentType)}, data: ${JSON.stringify(data)} },`
            );
        }
        lines.push(' ],');
    }
    lines.push('});');
    lines.push('');
    lines.push('const port = Number(process.env.PORT) || 4000;');
    lines.push('app.serve(port, () => {');
    lines.push(' console.log(`Server running on http://localhost:${port}`);');
    lines.push('});');

    return lines.join('\n');
}
